openapi: 3.0.3
info:
  title: Compute Service API
  description: >-
    This API allows interaction with a compute service that delegates tasks to a microservice.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8000
  - url: https://microservice-1-k15t.onrender.com
paths:
  /compute:
    get:
      summary: Compute a value by delegating to a microservice
      operationId: ComputeValue
      tags:
        - compute
      parameters:
        - name: number
          in: query
          description: The number to compute with
          required: true
          schema:
            type: integer
            example: 42
      responses:
        "200":
          description: Successful computation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 1764
        "400":
          description: Invalid request (e.g., missing or invalid number parameter)
        "500":
          description: Internal server error (e.g., microservice failure)
