openapi: 3.0.0
info:
  title: FastAPI Hello World API
  version: 1.0.0
  description: A simple Hello World API using FastAPI
servers:
  - url: 'http://localhost:8000'
    description: Local server
paths:
  /:
    get:
      summary: "Returns a Hello World message"
      operationId: "getHelloWorld"
      responses:
        '200':
          description: A JSON response with a Hello World message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
